// Code generated by rclgo-gen. DO NOT EDIT.

package action_msgs_msg

/*
#cgo LDFLAGS: "-L/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/lib" "-Wl,-rpath=/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/lib"
#cgo LDFLAGS: "-L/opt/ros/jazzy/lib" "-Wl,-rpath=/opt/ros/jazzy/lib"

#cgo LDFLAGS: -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -laction_msgs__rosidl_typesupport_c -laction_msgs__rosidl_generator_c
#cgo LDFLAGS: -lbuiltin_interfaces__rosidl_typesupport_c -lbuiltin_interfaces__rosidl_generator_c
#cgo LDFLAGS: -lunique_identifier_msgs__rosidl_typesupport_c -lunique_identifier_msgs__rosidl_generator_c

#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/action_msgs"
#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/builtin_interfaces"
#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/example_interfaces"
#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/geometry_msgs"
#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/sensor_msgs"
#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/std_msgs"
#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/std_srvs"
#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/test_msgs"
#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/builtin_interfaces"

#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/unique_identifier_msgs"

#cgo CFLAGS: "-I/home/voltamon48/ros_test/install/robo_op_sys_clt_lib/include/action_msgs"

#cgo CFLAGS: "-I/opt/ros/jazzy/include/action_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/builtin_interfaces"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/example_interfaces"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/geometry_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/sensor_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/std_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/std_srvs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/test_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/builtin_interfaces"

#cgo CFLAGS: "-I/opt/ros/jazzy/include/unique_identifier_msgs"

#cgo CFLAGS: "-I/opt/ros/jazzy/include/action_msgs"
*/
import "C"
