// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/is_discovery_running.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosbag2_interfaces/IsDiscoveryRunning", IsDiscoveryRunningTypeSupport)
	typemap.RegisterService("rosbag2_interfaces/srv/IsDiscoveryRunning", IsDiscoveryRunningTypeSupport)
}

type _IsDiscoveryRunningTypeSupport struct {}

func (s _IsDiscoveryRunningTypeSupport) Request() types.MessageTypeSupport {
	return IsDiscoveryRunning_RequestTypeSupport
}

func (s _IsDiscoveryRunningTypeSupport) Response() types.MessageTypeSupport {
	return IsDiscoveryRunning_ResponseTypeSupport
}

func (s _IsDiscoveryRunningTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__IsDiscoveryRunning())
}

// Modifying this variable is undefined behavior.
var IsDiscoveryRunningTypeSupport types.ServiceTypeSupport = _IsDiscoveryRunningTypeSupport{}

// IsDiscoveryRunningClient wraps rclgo.Client to provide type safe helper
// functions
type IsDiscoveryRunningClient struct {
	*rclgo.Client
}

// NewIsDiscoveryRunningClient creates and returns a new client for the
// IsDiscoveryRunning
func NewIsDiscoveryRunningClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*IsDiscoveryRunningClient, error) {
	client, err := node.NewClient(serviceName, IsDiscoveryRunningTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &IsDiscoveryRunningClient{client}, nil
}

func (s *IsDiscoveryRunningClient) Send(ctx context.Context, req *IsDiscoveryRunning_Request) (*IsDiscoveryRunning_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*IsDiscoveryRunning_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type IsDiscoveryRunningServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s IsDiscoveryRunningServiceResponseSender) SendResponse(resp *IsDiscoveryRunning_Response) error {
	return s.sender.SendResponse(resp)
}

type IsDiscoveryRunningServiceRequestHandler func(*rclgo.ServiceInfo, *IsDiscoveryRunning_Request, IsDiscoveryRunningServiceResponseSender)

// IsDiscoveryRunningService wraps rclgo.Service to provide type safe helper
// functions
type IsDiscoveryRunningService struct {
	*rclgo.Service
}

// NewIsDiscoveryRunningService creates and returns a new service for the
// IsDiscoveryRunning
func NewIsDiscoveryRunningService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler IsDiscoveryRunningServiceRequestHandler) (*IsDiscoveryRunningService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*IsDiscoveryRunning_Request)
		responseSender := IsDiscoveryRunningServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, IsDiscoveryRunningTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &IsDiscoveryRunningService{service}, nil
}