// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/is_discovery_running.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/IsDiscoveryRunning_Request", IsDiscoveryRunning_RequestTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/IsDiscoveryRunning_Request", IsDiscoveryRunning_RequestTypeSupport)
}

type IsDiscoveryRunning_Request struct {
}

// NewIsDiscoveryRunning_Request creates a new IsDiscoveryRunning_Request with default values.
func NewIsDiscoveryRunning_Request() *IsDiscoveryRunning_Request {
	self := IsDiscoveryRunning_Request{}
	self.SetDefaults()
	return &self
}

func (t *IsDiscoveryRunning_Request) Clone() *IsDiscoveryRunning_Request {
	c := &IsDiscoveryRunning_Request{}
	return c
}

func (t *IsDiscoveryRunning_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *IsDiscoveryRunning_Request) SetDefaults() {
}

func (t *IsDiscoveryRunning_Request) GetTypeSupport() types.MessageTypeSupport {
	return IsDiscoveryRunning_RequestTypeSupport
}

// IsDiscoveryRunning_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type IsDiscoveryRunning_RequestPublisher struct {
	*rclgo.Publisher
}

// NewIsDiscoveryRunning_RequestPublisher creates and returns a new publisher for the
// IsDiscoveryRunning_Request
func NewIsDiscoveryRunning_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*IsDiscoveryRunning_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, IsDiscoveryRunning_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &IsDiscoveryRunning_RequestPublisher{pub}, nil
}

func (p *IsDiscoveryRunning_RequestPublisher) Publish(msg *IsDiscoveryRunning_Request) error {
	return p.Publisher.Publish(msg)
}

// IsDiscoveryRunning_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type IsDiscoveryRunning_RequestSubscription struct {
	*rclgo.Subscription
}

// IsDiscoveryRunning_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a IsDiscoveryRunning_RequestSubscription.
type IsDiscoveryRunning_RequestSubscriptionCallback func(msg *IsDiscoveryRunning_Request, info *rclgo.MessageInfo, err error)

// NewIsDiscoveryRunning_RequestSubscription creates and returns a new subscription for the
// IsDiscoveryRunning_Request
func NewIsDiscoveryRunning_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback IsDiscoveryRunning_RequestSubscriptionCallback) (*IsDiscoveryRunning_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg IsDiscoveryRunning_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, IsDiscoveryRunning_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &IsDiscoveryRunning_RequestSubscription{sub}, nil
}

func (s *IsDiscoveryRunning_RequestSubscription) TakeMessage(out *IsDiscoveryRunning_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneIsDiscoveryRunning_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneIsDiscoveryRunning_RequestSlice(dst, src []IsDiscoveryRunning_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var IsDiscoveryRunning_RequestTypeSupport types.MessageTypeSupport = _IsDiscoveryRunning_RequestTypeSupport{}

type _IsDiscoveryRunning_RequestTypeSupport struct{}

func (t _IsDiscoveryRunning_RequestTypeSupport) New() types.Message {
	return NewIsDiscoveryRunning_Request()
}

func (t _IsDiscoveryRunning_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__IsDiscoveryRunning_Request
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__IsDiscoveryRunning_Request__create())
}

func (t _IsDiscoveryRunning_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__IsDiscoveryRunning_Request__destroy((*C.rosbag2_interfaces__srv__IsDiscoveryRunning_Request)(pointer_to_free))
}

func (t _IsDiscoveryRunning_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _IsDiscoveryRunning_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _IsDiscoveryRunning_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__IsDiscoveryRunning_Request())
}

type CIsDiscoveryRunning_Request = C.rosbag2_interfaces__srv__IsDiscoveryRunning_Request
type CIsDiscoveryRunning_Request__Sequence = C.rosbag2_interfaces__srv__IsDiscoveryRunning_Request__Sequence

func IsDiscoveryRunning_Request__Sequence_to_Go(goSlice *[]IsDiscoveryRunning_Request, cSlice CIsDiscoveryRunning_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]IsDiscoveryRunning_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		IsDiscoveryRunning_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func IsDiscoveryRunning_Request__Sequence_to_C(cSlice *CIsDiscoveryRunning_Request__Sequence, goSlice []IsDiscoveryRunning_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__IsDiscoveryRunning_Request)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__IsDiscoveryRunning_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		IsDiscoveryRunning_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func IsDiscoveryRunning_Request__Array_to_Go(goSlice []IsDiscoveryRunning_Request, cSlice []CIsDiscoveryRunning_Request) {
	for i := 0; i < len(cSlice); i++ {
		IsDiscoveryRunning_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func IsDiscoveryRunning_Request__Array_to_C(cSlice []CIsDiscoveryRunning_Request, goSlice []IsDiscoveryRunning_Request) {
	for i := 0; i < len(goSlice); i++ {
		IsDiscoveryRunning_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
