// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/is_discovery_running.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/IsDiscoveryRunning_Response", IsDiscoveryRunning_ResponseTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/IsDiscoveryRunning_Response", IsDiscoveryRunning_ResponseTypeSupport)
}

type IsDiscoveryRunning_Response struct {
	Running bool `yaml:"running"`// True if discovery is running, false otherwise
}

// NewIsDiscoveryRunning_Response creates a new IsDiscoveryRunning_Response with default values.
func NewIsDiscoveryRunning_Response() *IsDiscoveryRunning_Response {
	self := IsDiscoveryRunning_Response{}
	self.SetDefaults()
	return &self
}

func (t *IsDiscoveryRunning_Response) Clone() *IsDiscoveryRunning_Response {
	c := &IsDiscoveryRunning_Response{}
	c.Running = t.Running
	return c
}

func (t *IsDiscoveryRunning_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *IsDiscoveryRunning_Response) SetDefaults() {
	t.Running = false
}

func (t *IsDiscoveryRunning_Response) GetTypeSupport() types.MessageTypeSupport {
	return IsDiscoveryRunning_ResponseTypeSupport
}

// IsDiscoveryRunning_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type IsDiscoveryRunning_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewIsDiscoveryRunning_ResponsePublisher creates and returns a new publisher for the
// IsDiscoveryRunning_Response
func NewIsDiscoveryRunning_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*IsDiscoveryRunning_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, IsDiscoveryRunning_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &IsDiscoveryRunning_ResponsePublisher{pub}, nil
}

func (p *IsDiscoveryRunning_ResponsePublisher) Publish(msg *IsDiscoveryRunning_Response) error {
	return p.Publisher.Publish(msg)
}

// IsDiscoveryRunning_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type IsDiscoveryRunning_ResponseSubscription struct {
	*rclgo.Subscription
}

// IsDiscoveryRunning_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a IsDiscoveryRunning_ResponseSubscription.
type IsDiscoveryRunning_ResponseSubscriptionCallback func(msg *IsDiscoveryRunning_Response, info *rclgo.MessageInfo, err error)

// NewIsDiscoveryRunning_ResponseSubscription creates and returns a new subscription for the
// IsDiscoveryRunning_Response
func NewIsDiscoveryRunning_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback IsDiscoveryRunning_ResponseSubscriptionCallback) (*IsDiscoveryRunning_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg IsDiscoveryRunning_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, IsDiscoveryRunning_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &IsDiscoveryRunning_ResponseSubscription{sub}, nil
}

func (s *IsDiscoveryRunning_ResponseSubscription) TakeMessage(out *IsDiscoveryRunning_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneIsDiscoveryRunning_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneIsDiscoveryRunning_ResponseSlice(dst, src []IsDiscoveryRunning_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var IsDiscoveryRunning_ResponseTypeSupport types.MessageTypeSupport = _IsDiscoveryRunning_ResponseTypeSupport{}

type _IsDiscoveryRunning_ResponseTypeSupport struct{}

func (t _IsDiscoveryRunning_ResponseTypeSupport) New() types.Message {
	return NewIsDiscoveryRunning_Response()
}

func (t _IsDiscoveryRunning_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__IsDiscoveryRunning_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__IsDiscoveryRunning_Response__create())
}

func (t _IsDiscoveryRunning_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__IsDiscoveryRunning_Response__destroy((*C.rosbag2_interfaces__srv__IsDiscoveryRunning_Response)(pointer_to_free))
}

func (t _IsDiscoveryRunning_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*IsDiscoveryRunning_Response)
	mem := (*C.rosbag2_interfaces__srv__IsDiscoveryRunning_Response)(dst)
	mem.running = C.bool(m.Running)
}

func (t _IsDiscoveryRunning_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*IsDiscoveryRunning_Response)
	mem := (*C.rosbag2_interfaces__srv__IsDiscoveryRunning_Response)(ros2_message_buffer)
	m.Running = bool(mem.running)
}

func (t _IsDiscoveryRunning_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__IsDiscoveryRunning_Response())
}

type CIsDiscoveryRunning_Response = C.rosbag2_interfaces__srv__IsDiscoveryRunning_Response
type CIsDiscoveryRunning_Response__Sequence = C.rosbag2_interfaces__srv__IsDiscoveryRunning_Response__Sequence

func IsDiscoveryRunning_Response__Sequence_to_Go(goSlice *[]IsDiscoveryRunning_Response, cSlice CIsDiscoveryRunning_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]IsDiscoveryRunning_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		IsDiscoveryRunning_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func IsDiscoveryRunning_Response__Sequence_to_C(cSlice *CIsDiscoveryRunning_Response__Sequence, goSlice []IsDiscoveryRunning_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__IsDiscoveryRunning_Response)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__IsDiscoveryRunning_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		IsDiscoveryRunning_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func IsDiscoveryRunning_Response__Array_to_Go(goSlice []IsDiscoveryRunning_Response, cSlice []CIsDiscoveryRunning_Response) {
	for i := 0; i < len(cSlice); i++ {
		IsDiscoveryRunning_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func IsDiscoveryRunning_Response__Array_to_C(cSlice []CIsDiscoveryRunning_Response, goSlice []IsDiscoveryRunning_Response) {
	for i := 0; i < len(goSlice); i++ {
		IsDiscoveryRunning_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
