// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/record.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/Record_Request", Record_RequestTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/Record_Request", Record_RequestTypeSupport)
}

type Record_Request struct {
	Uri string `yaml:"uri"`// if provided, it will override the storage_options.uri provided during construction.Empty by default.
}

// NewRecord_Request creates a new Record_Request with default values.
func NewRecord_Request() *Record_Request {
	self := Record_Request{}
	self.SetDefaults()
	return &self
}

func (t *Record_Request) Clone() *Record_Request {
	c := &Record_Request{}
	c.Uri = t.Uri
	return c
}

func (t *Record_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Record_Request) SetDefaults() {
	t.Uri = ""
}

func (t *Record_Request) GetTypeSupport() types.MessageTypeSupport {
	return Record_RequestTypeSupport
}

// Record_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Record_RequestPublisher struct {
	*rclgo.Publisher
}

// NewRecord_RequestPublisher creates and returns a new publisher for the
// Record_Request
func NewRecord_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Record_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, Record_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Record_RequestPublisher{pub}, nil
}

func (p *Record_RequestPublisher) Publish(msg *Record_Request) error {
	return p.Publisher.Publish(msg)
}

// Record_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Record_RequestSubscription struct {
	*rclgo.Subscription
}

// Record_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a Record_RequestSubscription.
type Record_RequestSubscriptionCallback func(msg *Record_Request, info *rclgo.MessageInfo, err error)

// NewRecord_RequestSubscription creates and returns a new subscription for the
// Record_Request
func NewRecord_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Record_RequestSubscriptionCallback) (*Record_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Record_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Record_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Record_RequestSubscription{sub}, nil
}

func (s *Record_RequestSubscription) TakeMessage(out *Record_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneRecord_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneRecord_RequestSlice(dst, src []Record_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Record_RequestTypeSupport types.MessageTypeSupport = _Record_RequestTypeSupport{}

type _Record_RequestTypeSupport struct{}

func (t _Record_RequestTypeSupport) New() types.Message {
	return NewRecord_Request()
}

func (t _Record_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__Record_Request
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__Record_Request__create())
}

func (t _Record_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__Record_Request__destroy((*C.rosbag2_interfaces__srv__Record_Request)(pointer_to_free))
}

func (t _Record_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Record_Request)
	mem := (*C.rosbag2_interfaces__srv__Record_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.uri), m.Uri)
}

func (t _Record_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Record_Request)
	mem := (*C.rosbag2_interfaces__srv__Record_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.Uri, unsafe.Pointer(&mem.uri))
}

func (t _Record_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__Record_Request())
}

type CRecord_Request = C.rosbag2_interfaces__srv__Record_Request
type CRecord_Request__Sequence = C.rosbag2_interfaces__srv__Record_Request__Sequence

func Record_Request__Sequence_to_Go(goSlice *[]Record_Request, cSlice CRecord_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Record_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Record_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Record_Request__Sequence_to_C(cSlice *CRecord_Request__Sequence, goSlice []Record_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__Record_Request)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__Record_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Record_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Record_Request__Array_to_Go(goSlice []Record_Request, cSlice []CRecord_Request) {
	for i := 0; i < len(cSlice); i++ {
		Record_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Record_Request__Array_to_C(cSlice []CRecord_Request, goSlice []Record_Request) {
	for i := 0; i < len(goSlice); i++ {
		Record_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
