// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/record.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosbag2_interfaces/Record", RecordTypeSupport)
	typemap.RegisterService("rosbag2_interfaces/srv/Record", RecordTypeSupport)
}

type _RecordTypeSupport struct {}

func (s _RecordTypeSupport) Request() types.MessageTypeSupport {
	return Record_RequestTypeSupport
}

func (s _RecordTypeSupport) Response() types.MessageTypeSupport {
	return Record_ResponseTypeSupport
}

func (s _RecordTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__Record())
}

// Modifying this variable is undefined behavior.
var RecordTypeSupport types.ServiceTypeSupport = _RecordTypeSupport{}

// RecordClient wraps rclgo.Client to provide type safe helper
// functions
type RecordClient struct {
	*rclgo.Client
}

// NewRecordClient creates and returns a new client for the
// Record
func NewRecordClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*RecordClient, error) {
	client, err := node.NewClient(serviceName, RecordTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &RecordClient{client}, nil
}

func (s *RecordClient) Send(ctx context.Context, req *Record_Request) (*Record_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*Record_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type RecordServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s RecordServiceResponseSender) SendResponse(resp *Record_Response) error {
	return s.sender.SendResponse(resp)
}

type RecordServiceRequestHandler func(*rclgo.ServiceInfo, *Record_Request, RecordServiceResponseSender)

// RecordService wraps rclgo.Service to provide type safe helper
// functions
type RecordService struct {
	*rclgo.Service
}

// NewRecordService creates and returns a new service for the
// Record
func NewRecordService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler RecordServiceRequestHandler) (*RecordService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*Record_Request)
		responseSender := RecordServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, RecordTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &RecordService{service}, nil
}