// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/record.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/Record_Response", Record_ResponseTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/Record_Response", Record_ResponseTypeSupport)
}

type Record_Response struct {
	ReturnCode int32 `yaml:"return_code"`// Return code. Returns 1 when recording is already running or in case of error, otherwise 0.
	ErrorString string `yaml:"error_string"`// Error string. Empty if no error occurred.
}

// NewRecord_Response creates a new Record_Response with default values.
func NewRecord_Response() *Record_Response {
	self := Record_Response{}
	self.SetDefaults()
	return &self
}

func (t *Record_Response) Clone() *Record_Response {
	c := &Record_Response{}
	c.ReturnCode = t.ReturnCode
	c.ErrorString = t.ErrorString
	return c
}

func (t *Record_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Record_Response) SetDefaults() {
	t.ReturnCode = 0
	t.ErrorString = ""
}

func (t *Record_Response) GetTypeSupport() types.MessageTypeSupport {
	return Record_ResponseTypeSupport
}

// Record_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Record_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewRecord_ResponsePublisher creates and returns a new publisher for the
// Record_Response
func NewRecord_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Record_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, Record_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Record_ResponsePublisher{pub}, nil
}

func (p *Record_ResponsePublisher) Publish(msg *Record_Response) error {
	return p.Publisher.Publish(msg)
}

// Record_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Record_ResponseSubscription struct {
	*rclgo.Subscription
}

// Record_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a Record_ResponseSubscription.
type Record_ResponseSubscriptionCallback func(msg *Record_Response, info *rclgo.MessageInfo, err error)

// NewRecord_ResponseSubscription creates and returns a new subscription for the
// Record_Response
func NewRecord_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Record_ResponseSubscriptionCallback) (*Record_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Record_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Record_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Record_ResponseSubscription{sub}, nil
}

func (s *Record_ResponseSubscription) TakeMessage(out *Record_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneRecord_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneRecord_ResponseSlice(dst, src []Record_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Record_ResponseTypeSupport types.MessageTypeSupport = _Record_ResponseTypeSupport{}

type _Record_ResponseTypeSupport struct{}

func (t _Record_ResponseTypeSupport) New() types.Message {
	return NewRecord_Response()
}

func (t _Record_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__Record_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__Record_Response__create())
}

func (t _Record_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__Record_Response__destroy((*C.rosbag2_interfaces__srv__Record_Response)(pointer_to_free))
}

func (t _Record_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Record_Response)
	mem := (*C.rosbag2_interfaces__srv__Record_Response)(dst)
	mem.return_code = C.int32_t(m.ReturnCode)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.error_string), m.ErrorString)
}

func (t _Record_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Record_Response)
	mem := (*C.rosbag2_interfaces__srv__Record_Response)(ros2_message_buffer)
	m.ReturnCode = int32(mem.return_code)
	primitives.StringAsGoStruct(&m.ErrorString, unsafe.Pointer(&mem.error_string))
}

func (t _Record_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__Record_Response())
}

type CRecord_Response = C.rosbag2_interfaces__srv__Record_Response
type CRecord_Response__Sequence = C.rosbag2_interfaces__srv__Record_Response__Sequence

func Record_Response__Sequence_to_Go(goSlice *[]Record_Response, cSlice CRecord_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Record_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Record_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Record_Response__Sequence_to_C(cSlice *CRecord_Response__Sequence, goSlice []Record_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__Record_Response)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__Record_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Record_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Record_Response__Array_to_Go(goSlice []Record_Response, cSlice []CRecord_Response) {
	for i := 0; i < len(cSlice); i++ {
		Record_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Record_Response__Array_to_C(cSlice []CRecord_Response, goSlice []Record_Response) {
	for i := 0; i < len(goSlice); i++ {
		Record_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
