// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/start_discovery.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/StartDiscovery_Response", StartDiscovery_ResponseTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/StartDiscovery_Response", StartDiscovery_ResponseTypeSupport)
}

type StartDiscovery_Response struct {
	ReturnCode int32 `yaml:"return_code"`// Return code. Returns 1 when discovery is already running or in case of error, otherwise 0.
	ErrorString string `yaml:"error_string"`// Error string. Empty if no error occurred.
}

// NewStartDiscovery_Response creates a new StartDiscovery_Response with default values.
func NewStartDiscovery_Response() *StartDiscovery_Response {
	self := StartDiscovery_Response{}
	self.SetDefaults()
	return &self
}

func (t *StartDiscovery_Response) Clone() *StartDiscovery_Response {
	c := &StartDiscovery_Response{}
	c.ReturnCode = t.ReturnCode
	c.ErrorString = t.ErrorString
	return c
}

func (t *StartDiscovery_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *StartDiscovery_Response) SetDefaults() {
	t.ReturnCode = 0
	t.ErrorString = ""
}

func (t *StartDiscovery_Response) GetTypeSupport() types.MessageTypeSupport {
	return StartDiscovery_ResponseTypeSupport
}

// StartDiscovery_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type StartDiscovery_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewStartDiscovery_ResponsePublisher creates and returns a new publisher for the
// StartDiscovery_Response
func NewStartDiscovery_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*StartDiscovery_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, StartDiscovery_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &StartDiscovery_ResponsePublisher{pub}, nil
}

func (p *StartDiscovery_ResponsePublisher) Publish(msg *StartDiscovery_Response) error {
	return p.Publisher.Publish(msg)
}

// StartDiscovery_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type StartDiscovery_ResponseSubscription struct {
	*rclgo.Subscription
}

// StartDiscovery_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a StartDiscovery_ResponseSubscription.
type StartDiscovery_ResponseSubscriptionCallback func(msg *StartDiscovery_Response, info *rclgo.MessageInfo, err error)

// NewStartDiscovery_ResponseSubscription creates and returns a new subscription for the
// StartDiscovery_Response
func NewStartDiscovery_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback StartDiscovery_ResponseSubscriptionCallback) (*StartDiscovery_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg StartDiscovery_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, StartDiscovery_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &StartDiscovery_ResponseSubscription{sub}, nil
}

func (s *StartDiscovery_ResponseSubscription) TakeMessage(out *StartDiscovery_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneStartDiscovery_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneStartDiscovery_ResponseSlice(dst, src []StartDiscovery_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var StartDiscovery_ResponseTypeSupport types.MessageTypeSupport = _StartDiscovery_ResponseTypeSupport{}

type _StartDiscovery_ResponseTypeSupport struct{}

func (t _StartDiscovery_ResponseTypeSupport) New() types.Message {
	return NewStartDiscovery_Response()
}

func (t _StartDiscovery_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__StartDiscovery_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__StartDiscovery_Response__create())
}

func (t _StartDiscovery_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__StartDiscovery_Response__destroy((*C.rosbag2_interfaces__srv__StartDiscovery_Response)(pointer_to_free))
}

func (t _StartDiscovery_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*StartDiscovery_Response)
	mem := (*C.rosbag2_interfaces__srv__StartDiscovery_Response)(dst)
	mem.return_code = C.int32_t(m.ReturnCode)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.error_string), m.ErrorString)
}

func (t _StartDiscovery_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*StartDiscovery_Response)
	mem := (*C.rosbag2_interfaces__srv__StartDiscovery_Response)(ros2_message_buffer)
	m.ReturnCode = int32(mem.return_code)
	primitives.StringAsGoStruct(&m.ErrorString, unsafe.Pointer(&mem.error_string))
}

func (t _StartDiscovery_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__StartDiscovery_Response())
}

type CStartDiscovery_Response = C.rosbag2_interfaces__srv__StartDiscovery_Response
type CStartDiscovery_Response__Sequence = C.rosbag2_interfaces__srv__StartDiscovery_Response__Sequence

func StartDiscovery_Response__Sequence_to_Go(goSlice *[]StartDiscovery_Response, cSlice CStartDiscovery_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]StartDiscovery_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		StartDiscovery_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func StartDiscovery_Response__Sequence_to_C(cSlice *CStartDiscovery_Response__Sequence, goSlice []StartDiscovery_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__StartDiscovery_Response)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__StartDiscovery_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		StartDiscovery_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func StartDiscovery_Response__Array_to_Go(goSlice []StartDiscovery_Response, cSlice []CStartDiscovery_Response) {
	for i := 0; i < len(cSlice); i++ {
		StartDiscovery_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func StartDiscovery_Response__Array_to_C(cSlice []CStartDiscovery_Response, goSlice []StartDiscovery_Response) {
	for i := 0; i < len(goSlice); i++ {
		StartDiscovery_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
