// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/start_discovery.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/StartDiscovery_Request", StartDiscovery_RequestTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/StartDiscovery_Request", StartDiscovery_RequestTypeSupport)
}

type StartDiscovery_Request struct {
}

// NewStartDiscovery_Request creates a new StartDiscovery_Request with default values.
func NewStartDiscovery_Request() *StartDiscovery_Request {
	self := StartDiscovery_Request{}
	self.SetDefaults()
	return &self
}

func (t *StartDiscovery_Request) Clone() *StartDiscovery_Request {
	c := &StartDiscovery_Request{}
	return c
}

func (t *StartDiscovery_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *StartDiscovery_Request) SetDefaults() {
}

func (t *StartDiscovery_Request) GetTypeSupport() types.MessageTypeSupport {
	return StartDiscovery_RequestTypeSupport
}

// StartDiscovery_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type StartDiscovery_RequestPublisher struct {
	*rclgo.Publisher
}

// NewStartDiscovery_RequestPublisher creates and returns a new publisher for the
// StartDiscovery_Request
func NewStartDiscovery_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*StartDiscovery_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, StartDiscovery_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &StartDiscovery_RequestPublisher{pub}, nil
}

func (p *StartDiscovery_RequestPublisher) Publish(msg *StartDiscovery_Request) error {
	return p.Publisher.Publish(msg)
}

// StartDiscovery_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type StartDiscovery_RequestSubscription struct {
	*rclgo.Subscription
}

// StartDiscovery_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a StartDiscovery_RequestSubscription.
type StartDiscovery_RequestSubscriptionCallback func(msg *StartDiscovery_Request, info *rclgo.MessageInfo, err error)

// NewStartDiscovery_RequestSubscription creates and returns a new subscription for the
// StartDiscovery_Request
func NewStartDiscovery_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback StartDiscovery_RequestSubscriptionCallback) (*StartDiscovery_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg StartDiscovery_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, StartDiscovery_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &StartDiscovery_RequestSubscription{sub}, nil
}

func (s *StartDiscovery_RequestSubscription) TakeMessage(out *StartDiscovery_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneStartDiscovery_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneStartDiscovery_RequestSlice(dst, src []StartDiscovery_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var StartDiscovery_RequestTypeSupport types.MessageTypeSupport = _StartDiscovery_RequestTypeSupport{}

type _StartDiscovery_RequestTypeSupport struct{}

func (t _StartDiscovery_RequestTypeSupport) New() types.Message {
	return NewStartDiscovery_Request()
}

func (t _StartDiscovery_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__StartDiscovery_Request
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__StartDiscovery_Request__create())
}

func (t _StartDiscovery_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__StartDiscovery_Request__destroy((*C.rosbag2_interfaces__srv__StartDiscovery_Request)(pointer_to_free))
}

func (t _StartDiscovery_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _StartDiscovery_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _StartDiscovery_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__StartDiscovery_Request())
}

type CStartDiscovery_Request = C.rosbag2_interfaces__srv__StartDiscovery_Request
type CStartDiscovery_Request__Sequence = C.rosbag2_interfaces__srv__StartDiscovery_Request__Sequence

func StartDiscovery_Request__Sequence_to_Go(goSlice *[]StartDiscovery_Request, cSlice CStartDiscovery_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]StartDiscovery_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		StartDiscovery_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func StartDiscovery_Request__Sequence_to_C(cSlice *CStartDiscovery_Request__Sequence, goSlice []StartDiscovery_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__StartDiscovery_Request)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__StartDiscovery_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		StartDiscovery_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func StartDiscovery_Request__Array_to_Go(goSlice []StartDiscovery_Request, cSlice []CStartDiscovery_Request) {
	for i := 0; i < len(cSlice); i++ {
		StartDiscovery_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func StartDiscovery_Request__Array_to_C(cSlice []CStartDiscovery_Request, goSlice []StartDiscovery_Request) {
	for i := 0; i < len(goSlice); i++ {
		StartDiscovery_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
