// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/start_discovery.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosbag2_interfaces/StartDiscovery", StartDiscoveryTypeSupport)
	typemap.RegisterService("rosbag2_interfaces/srv/StartDiscovery", StartDiscoveryTypeSupport)
}

type _StartDiscoveryTypeSupport struct {}

func (s _StartDiscoveryTypeSupport) Request() types.MessageTypeSupport {
	return StartDiscovery_RequestTypeSupport
}

func (s _StartDiscoveryTypeSupport) Response() types.MessageTypeSupport {
	return StartDiscovery_ResponseTypeSupport
}

func (s _StartDiscoveryTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__StartDiscovery())
}

// Modifying this variable is undefined behavior.
var StartDiscoveryTypeSupport types.ServiceTypeSupport = _StartDiscoveryTypeSupport{}

// StartDiscoveryClient wraps rclgo.Client to provide type safe helper
// functions
type StartDiscoveryClient struct {
	*rclgo.Client
}

// NewStartDiscoveryClient creates and returns a new client for the
// StartDiscovery
func NewStartDiscoveryClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*StartDiscoveryClient, error) {
	client, err := node.NewClient(serviceName, StartDiscoveryTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &StartDiscoveryClient{client}, nil
}

func (s *StartDiscoveryClient) Send(ctx context.Context, req *StartDiscovery_Request) (*StartDiscovery_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*StartDiscovery_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type StartDiscoveryServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s StartDiscoveryServiceResponseSender) SendResponse(resp *StartDiscovery_Response) error {
	return s.sender.SendResponse(resp)
}

type StartDiscoveryServiceRequestHandler func(*rclgo.ServiceInfo, *StartDiscovery_Request, StartDiscoveryServiceResponseSender)

// StartDiscoveryService wraps rclgo.Service to provide type safe helper
// functions
type StartDiscoveryService struct {
	*rclgo.Service
}

// NewStartDiscoveryService creates and returns a new service for the
// StartDiscovery
func NewStartDiscoveryService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler StartDiscoveryServiceRequestHandler) (*StartDiscoveryService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*StartDiscovery_Request)
		responseSender := StartDiscoveryServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, StartDiscoveryTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &StartDiscoveryService{service}, nil
}