// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/stop_discovery.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/StopDiscovery_Request", StopDiscovery_RequestTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/StopDiscovery_Request", StopDiscovery_RequestTypeSupport)
}

type StopDiscovery_Request struct {
}

// NewStopDiscovery_Request creates a new StopDiscovery_Request with default values.
func NewStopDiscovery_Request() *StopDiscovery_Request {
	self := StopDiscovery_Request{}
	self.SetDefaults()
	return &self
}

func (t *StopDiscovery_Request) Clone() *StopDiscovery_Request {
	c := &StopDiscovery_Request{}
	return c
}

func (t *StopDiscovery_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *StopDiscovery_Request) SetDefaults() {
}

func (t *StopDiscovery_Request) GetTypeSupport() types.MessageTypeSupport {
	return StopDiscovery_RequestTypeSupport
}

// StopDiscovery_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type StopDiscovery_RequestPublisher struct {
	*rclgo.Publisher
}

// NewStopDiscovery_RequestPublisher creates and returns a new publisher for the
// StopDiscovery_Request
func NewStopDiscovery_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*StopDiscovery_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, StopDiscovery_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &StopDiscovery_RequestPublisher{pub}, nil
}

func (p *StopDiscovery_RequestPublisher) Publish(msg *StopDiscovery_Request) error {
	return p.Publisher.Publish(msg)
}

// StopDiscovery_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type StopDiscovery_RequestSubscription struct {
	*rclgo.Subscription
}

// StopDiscovery_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a StopDiscovery_RequestSubscription.
type StopDiscovery_RequestSubscriptionCallback func(msg *StopDiscovery_Request, info *rclgo.MessageInfo, err error)

// NewStopDiscovery_RequestSubscription creates and returns a new subscription for the
// StopDiscovery_Request
func NewStopDiscovery_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback StopDiscovery_RequestSubscriptionCallback) (*StopDiscovery_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg StopDiscovery_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, StopDiscovery_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &StopDiscovery_RequestSubscription{sub}, nil
}

func (s *StopDiscovery_RequestSubscription) TakeMessage(out *StopDiscovery_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneStopDiscovery_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneStopDiscovery_RequestSlice(dst, src []StopDiscovery_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var StopDiscovery_RequestTypeSupport types.MessageTypeSupport = _StopDiscovery_RequestTypeSupport{}

type _StopDiscovery_RequestTypeSupport struct{}

func (t _StopDiscovery_RequestTypeSupport) New() types.Message {
	return NewStopDiscovery_Request()
}

func (t _StopDiscovery_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__StopDiscovery_Request
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__StopDiscovery_Request__create())
}

func (t _StopDiscovery_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__StopDiscovery_Request__destroy((*C.rosbag2_interfaces__srv__StopDiscovery_Request)(pointer_to_free))
}

func (t _StopDiscovery_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _StopDiscovery_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _StopDiscovery_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__StopDiscovery_Request())
}

type CStopDiscovery_Request = C.rosbag2_interfaces__srv__StopDiscovery_Request
type CStopDiscovery_Request__Sequence = C.rosbag2_interfaces__srv__StopDiscovery_Request__Sequence

func StopDiscovery_Request__Sequence_to_Go(goSlice *[]StopDiscovery_Request, cSlice CStopDiscovery_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]StopDiscovery_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		StopDiscovery_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func StopDiscovery_Request__Sequence_to_C(cSlice *CStopDiscovery_Request__Sequence, goSlice []StopDiscovery_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__StopDiscovery_Request)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__StopDiscovery_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		StopDiscovery_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func StopDiscovery_Request__Array_to_Go(goSlice []StopDiscovery_Request, cSlice []CStopDiscovery_Request) {
	for i := 0; i < len(cSlice); i++ {
		StopDiscovery_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func StopDiscovery_Request__Array_to_C(cSlice []CStopDiscovery_Request, goSlice []StopDiscovery_Request) {
	for i := 0; i < len(goSlice); i++ {
		StopDiscovery_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
