// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/stop_discovery.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/StopDiscovery_Response", StopDiscovery_ResponseTypeSupport)
	typemap.RegisterMessage("rosbag2_interfaces/srv/StopDiscovery_Response", StopDiscovery_ResponseTypeSupport)
}

type StopDiscovery_Response struct {
	ReturnCode int32 `yaml:"return_code"`// Return code. Returns 1 when discovery is not running, otherwise 0.
	ErrorString string `yaml:"error_string"`// Error string. Empty if no error occurred.
}

// NewStopDiscovery_Response creates a new StopDiscovery_Response with default values.
func NewStopDiscovery_Response() *StopDiscovery_Response {
	self := StopDiscovery_Response{}
	self.SetDefaults()
	return &self
}

func (t *StopDiscovery_Response) Clone() *StopDiscovery_Response {
	c := &StopDiscovery_Response{}
	c.ReturnCode = t.ReturnCode
	c.ErrorString = t.ErrorString
	return c
}

func (t *StopDiscovery_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *StopDiscovery_Response) SetDefaults() {
	t.ReturnCode = 0
	t.ErrorString = ""
}

func (t *StopDiscovery_Response) GetTypeSupport() types.MessageTypeSupport {
	return StopDiscovery_ResponseTypeSupport
}

// StopDiscovery_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type StopDiscovery_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewStopDiscovery_ResponsePublisher creates and returns a new publisher for the
// StopDiscovery_Response
func NewStopDiscovery_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*StopDiscovery_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, StopDiscovery_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &StopDiscovery_ResponsePublisher{pub}, nil
}

func (p *StopDiscovery_ResponsePublisher) Publish(msg *StopDiscovery_Response) error {
	return p.Publisher.Publish(msg)
}

// StopDiscovery_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type StopDiscovery_ResponseSubscription struct {
	*rclgo.Subscription
}

// StopDiscovery_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a StopDiscovery_ResponseSubscription.
type StopDiscovery_ResponseSubscriptionCallback func(msg *StopDiscovery_Response, info *rclgo.MessageInfo, err error)

// NewStopDiscovery_ResponseSubscription creates and returns a new subscription for the
// StopDiscovery_Response
func NewStopDiscovery_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback StopDiscovery_ResponseSubscriptionCallback) (*StopDiscovery_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg StopDiscovery_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, StopDiscovery_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &StopDiscovery_ResponseSubscription{sub}, nil
}

func (s *StopDiscovery_ResponseSubscription) TakeMessage(out *StopDiscovery_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneStopDiscovery_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneStopDiscovery_ResponseSlice(dst, src []StopDiscovery_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var StopDiscovery_ResponseTypeSupport types.MessageTypeSupport = _StopDiscovery_ResponseTypeSupport{}

type _StopDiscovery_ResponseTypeSupport struct{}

func (t _StopDiscovery_ResponseTypeSupport) New() types.Message {
	return NewStopDiscovery_Response()
}

func (t _StopDiscovery_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__StopDiscovery_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__StopDiscovery_Response__create())
}

func (t _StopDiscovery_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__StopDiscovery_Response__destroy((*C.rosbag2_interfaces__srv__StopDiscovery_Response)(pointer_to_free))
}

func (t _StopDiscovery_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*StopDiscovery_Response)
	mem := (*C.rosbag2_interfaces__srv__StopDiscovery_Response)(dst)
	mem.return_code = C.int32_t(m.ReturnCode)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.error_string), m.ErrorString)
}

func (t _StopDiscovery_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*StopDiscovery_Response)
	mem := (*C.rosbag2_interfaces__srv__StopDiscovery_Response)(ros2_message_buffer)
	m.ReturnCode = int32(mem.return_code)
	primitives.StringAsGoStruct(&m.ErrorString, unsafe.Pointer(&mem.error_string))
}

func (t _StopDiscovery_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__StopDiscovery_Response())
}

type CStopDiscovery_Response = C.rosbag2_interfaces__srv__StopDiscovery_Response
type CStopDiscovery_Response__Sequence = C.rosbag2_interfaces__srv__StopDiscovery_Response__Sequence

func StopDiscovery_Response__Sequence_to_Go(goSlice *[]StopDiscovery_Response, cSlice CStopDiscovery_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]StopDiscovery_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		StopDiscovery_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func StopDiscovery_Response__Sequence_to_C(cSlice *CStopDiscovery_Response__Sequence, goSlice []StopDiscovery_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__StopDiscovery_Response)(C.malloc(C.sizeof_struct_rosbag2_interfaces__srv__StopDiscovery_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		StopDiscovery_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func StopDiscovery_Response__Array_to_Go(goSlice []StopDiscovery_Response, cSlice []CStopDiscovery_Response) {
	for i := 0; i < len(cSlice); i++ {
		StopDiscovery_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func StopDiscovery_Response__Array_to_C(cSlice []CStopDiscovery_Response, goSlice []StopDiscovery_Response) {
	for i := 0; i < len(goSlice); i++ {
		StopDiscovery_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
