// Code generated by rclgo-gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/stop_discovery.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosbag2_interfaces/StopDiscovery", StopDiscoveryTypeSupport)
	typemap.RegisterService("rosbag2_interfaces/srv/StopDiscovery", StopDiscoveryTypeSupport)
}

type _StopDiscoveryTypeSupport struct {}

func (s _StopDiscoveryTypeSupport) Request() types.MessageTypeSupport {
	return StopDiscovery_RequestTypeSupport
}

func (s _StopDiscoveryTypeSupport) Response() types.MessageTypeSupport {
	return StopDiscovery_ResponseTypeSupport
}

func (s _StopDiscoveryTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__StopDiscovery())
}

// Modifying this variable is undefined behavior.
var StopDiscoveryTypeSupport types.ServiceTypeSupport = _StopDiscoveryTypeSupport{}

// StopDiscoveryClient wraps rclgo.Client to provide type safe helper
// functions
type StopDiscoveryClient struct {
	*rclgo.Client
}

// NewStopDiscoveryClient creates and returns a new client for the
// StopDiscovery
func NewStopDiscoveryClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*StopDiscoveryClient, error) {
	client, err := node.NewClient(serviceName, StopDiscoveryTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &StopDiscoveryClient{client}, nil
}

func (s *StopDiscoveryClient) Send(ctx context.Context, req *StopDiscovery_Request) (*StopDiscovery_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*StopDiscovery_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type StopDiscoveryServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s StopDiscoveryServiceResponseSender) SendResponse(resp *StopDiscovery_Response) error {
	return s.sender.SendResponse(resp)
}

type StopDiscoveryServiceRequestHandler func(*rclgo.ServiceInfo, *StopDiscovery_Request, StopDiscoveryServiceResponseSender)

// StopDiscoveryService wraps rclgo.Service to provide type safe helper
// functions
type StopDiscoveryService struct {
	*rclgo.Service
}

// NewStopDiscoveryService creates and returns a new service for the
// StopDiscovery
func NewStopDiscoveryService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler StopDiscoveryServiceRequestHandler) (*StopDiscoveryService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*StopDiscovery_Request)
		responseSender := StopDiscoveryServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, StopDiscoveryTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &StopDiscoveryService{service}, nil
}